name: CI
on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      ruby-version: ${{ steps.set.outputs.ruby }}
    steps:
      - id: set
        run: echo "ruby=3.3.5" >> $GITHUB_OUTPUT

  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true
      - run: bundle exec rubocop -f github

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true
      - run: bundle exec rake
